import type { Metadata } from "next";
import { Inter } from 'next/font/google';
import "./globals.css";
// import Navbar from "@/components/ui/navbar";

const inter = Inter({
  variable: '--font-inter',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.variable} antialiased`}
      >
        {/* <Navbar /> */}
        <main className="max-w-[1300px] mx-auto">
        {children}
        </main>
      </body>
    </html>
  );
}
